services:
  backend:
    build:
      context: ./weather_app_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./weather_app_backend:/code
    depends_on:
      - db
    env_file:
      - /env/.env

  db:
    image: mongo:6.0
    volumes:
      - mongodb_data:/data/db
    env_file:
      - /env/.env
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./weather_app_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./weather_app_frontend/src:/app/src
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    depends_on:
      - backend

volumes:
  mongodb_data:
